const {test} = require('node:test');
const assert = require('node:assert/strict');
const core = require('../assets/js/brief-core.js');
const valid = {business:'Example workshop',name:'Test Person',email:'person@example.com',website:'https://example.com',projectType:'A new website',goal:'Explain our services clearly.',needs:['Business and service information'],style:['Warm and personal'],content:['Written content']};
test('starts with a complete blank schema',()=>{const a=core.sanitize(null);assert.equal(a.business,'');assert.deepEqual(a.needs,[]);assert.equal(Object.keys(a).length,15)});
test('requires a non-blank business name',()=>{assert.ok(core.validateStep(0,{business:'  '}).business)});
test('valid first step and optional blank contact fields pass',()=>{assert.deepEqual(core.validateStep(0,{business:'Example'}),{});assert.deepEqual(core.validateStep(0,valid),{})});
test('rejects malformed email but permits whitespace around valid email',()=>{assert.ok(core.validateStep(0,{...valid,email:'bad@'}).email);assert.deepEqual(core.validateStep(0,{...valid,email:' person@example.com '}),{})});
test('validates web protocol and denies credential-bearing URLs',()=>{for(const website of ['javascript:alert(1)','ftp://example.com','https://user:password@example.com','example.com','https://localhost'])assert.ok(core.validateStep(0,{...valid,website}).website);assert.deepEqual(core.validateStep(0,{...valid,website:'https://example.com/path'}),{})});
test('goal and project type are required',()=>{const e=core.validateStep(1,{});assert.ok(e.goal);assert.ok(e.projectType);assert.deepEqual(core.validateStep(1,valid),{})});
test('undecided is a valid project answer',()=>assert.deepEqual(core.validateStep(1,{projectType:'I’m still figuring it out',goal:'Explore options'}),{}));
test('later preferences are optional',()=>{assert.deepEqual(core.validateStep(2,{}),{});assert.deepEqual(core.validateStep(3,{}),{})});
test('unrecognized values and arbitrary keys are dropped',()=>{const a=core.sanitize({...valid,projectType:'made-up',token:'private',style:['Warm and personal','bad','Warm and personal']});assert.equal(a.projectType,'');assert.equal(a.token,undefined);assert.deepEqual(a.style,['Warm and personal'])});
test('text lengths are bounded',()=>{assert.equal(core.sanitize({business:'a'.repeat(1000)}).business.length,120)});
test('stored draft round-trips',()=>{const state=core.restore(JSON.stringify({version:1,answers:valid,step:3}));assert.equal(state.step,3);assert.equal(state.answers.business,valid.business)});
test('invalid saved version and broken JSON are rejected',()=>{assert.throws(()=>core.restore('{broken'));assert.throws(()=>core.restore(JSON.stringify({version:2,answers:valid})));assert.throws(()=>core.restore('{}'))});
test('step index is bounded',()=>{assert.equal(core.restore(JSON.stringify({version:1,answers:valid,step:100})).step,4);assert.equal(core.restore(JSON.stringify({version:1,answers:valid,step:-2})).step,0)});
test('plain-text export accurately includes values and non-submission state',()=>{const text=core.toText(valid);assert.ok(text.includes('LOCAL PREVIEW · Not submitted'));assert.ok(text.includes('Business or project: Example workshop'));assert.ok(text.includes('Additional notes: Not specified'));assert.ok(text.includes('not been sent to VDS or Notion'))});
test('HTML-like answers remain plain text, never interpreted by core',()=>{const a=core.sanitize({...valid,business:'<img onerror=alert(1)>'});assert.equal(a.business,'<img onerror=alert(1)>');assert.ok(core.toText(a).includes('<img onerror=alert(1)>'))});
test('download filenames are safe and bounded',()=>{assert.equal(core.filename({business:'José & Company / ../'}),'jose-company-brief.txt');assert.equal(core.filename({business:'😎'}),'vds-project-brief.txt');assert.ok(core.filename({business:'a'.repeat(300)}).length<=70)});
