const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const setup=async()=>{
 const {PGlite}=await import('@electric-sql/pglite');const db=new PGlite();await db.exec(await fs.readFile(path.join(__dirname,'../database/staging-design.sql'),'utf8'));
 const {PostgresCustomerRepository,PostgresOutbox}=await import('../src/postgres-customer.mjs');
 const principal={provider:'supabase',id:'synthetic-juan'},customer='synthetic-pesmera',workspace='synthetic-workspace';
 await db.query("INSERT INTO vds_intake.assignments(workspace,provider,subject,customer,template,expires_at) VALUES($1,$2,$3,$4,'synthetic-v1',now()+interval '1 day')",[workspace,principal.provider,principal.id,customer]);
 const answers={inventory:[{id:'chair',name:'Synthetic chair',decision:'correct',quantity:10,priceCents:1234,baseVersion:0}],packages:[],closing:['Follow-up only'],language:'Both'};
 return {db,repo:new PostgresCustomerRepository(db),outbox:new PostgresOutbox(db),principal,customer,workspace,answers};
};
test('local PostgreSQL: durable revisions, immutable snapshot and tenant isolation',async()=>{const f=await setup();try{await f.repo.save(f.principal,f.customer,{expectedRevision:0,answers:f.answers});const {PostgresCustomerRepository}=await import('../src/postgres-customer.mjs');assert.equal((await new PostgresCustomerRepository(f.db).load(f.principal,f.customer)).revision,1);await assert.rejects(f.repo.load({...f.principal,id:'other'},f.customer),e=>e.code==='ACCESS_DENIED');await assert.rejects(f.repo.save(f.principal,f.customer,{expectedRevision:0,answers:f.answers}),e=>e.code==='DRAFT_CONFLICT');assert.equal((await f.db.query('SELECT count(*)::int AS n FROM vds_intake.versions')).rows[0].n,1);}finally{await f.db.close();}});
test('local PostgreSQL: separate repositories queue one submission/outbox on duplicate calls',async()=>{const f=await setup();try{await f.repo.save(f.principal,f.customer,{expectedRevision:0,answers:f.answers});const results=await Promise.all([f.repo.submit(f.principal,f.customer,1),f.repo.submit(f.principal,f.customer,1)]);assert.equal(results[0].id,results[1].id);assert.equal((await f.db.query('SELECT count(*)::int AS n FROM vds_intake.outbox')).rows[0].n,1);f.answers.closing.push('New');await f.repo.save(f.principal,f.customer,{expectedRevision:1,answers:f.answers});assert.equal((await f.repo.submit(f.principal,f.customer,1)).id,results[0].id);assert.equal((await f.db.query('SELECT payload FROM vds_intake.versions WHERE revision=1')).rows[0].payload.answers.closing.length,1);}finally{await f.db.close();}});
test('local PostgreSQL: rollback makes draft+version atomic after interrupted insert',async()=>{const f=await setup();try{const bad={transaction:cb=>f.db.transaction(tx=>cb({query:async(sql,params)=>{if(sql.startsWith('INSERT INTO vds_intake.drafts'))throw Error('synthetic interruption');return tx.query(sql,params);}}))};const {PostgresCustomerRepository}=await import('../src/postgres-customer.mjs');await assert.rejects(new PostgresCustomerRepository(bad).save(f.principal,f.customer,{expectedRevision:0,answers:f.answers}));assert.equal((await f.db.query('SELECT count(*)::int AS n FROM vds_intake.versions')).rows[0].n,0);}finally{await f.db.close();}});
test('local PostgreSQL: worker leases, fencing, receipt binding and recovery',async()=>{const f=await setup();try{await f.repo.save(f.principal,f.customer,{expectedRevision:0,answers:f.answers});const s=await f.repo.submit(f.principal,f.customer,1),first=await f.outbox.claim('worker-a');assert.equal(await f.outbox.claim('worker-b'),null);await f.outbox.markCreateAttempt(first.lease);await f.db.query("UPDATE vds_intake.outbox SET lease_until=now()-interval '1 second'");const second=await f.outbox.claim('worker-b');assert.equal(second.lease.create_attempted,true);await assert.rejects(f.outbox.finish(first.lease,{verified:false}),e=>e.code==='LEASE_LOST');await assert.rejects(f.outbox.finish(second.lease,{verified:true,id:s.id,digest:'wrong',notionUrl:'https://app.notion.com/p/synthetic'}),e=>e.code==='UNVERIFIED_RECEIPT');await f.outbox.finish(second.lease,{verified:true,id:s.id,digest:s.digest,notionUrl:'https://app.notion.com/p/synthetic'});assert.equal((await f.repo.receipt(f.principal,f.customer,1)).status,'verified');assert.equal((await f.repo.receipt(f.principal,f.customer,1)).update_status,'disabled');assert.equal(await f.outbox.claim('worker-c'),null);}finally{await f.db.close();}});
test('local PostgreSQL: expired/revoked assignment denies stored draft',async()=>{const f=await setup();try{await f.repo.save(f.principal,f.customer,{expectedRevision:0,answers:f.answers});await f.db.query('UPDATE vds_intake.assignments SET revoked=true');await assert.rejects(f.repo.load(f.principal,f.customer),e=>e.code==='ACCESS_DENIED');}finally{await f.db.close();}});
test('local PostgreSQL: RLS applies to unprivileged fixture role and immutable permissions',async()=>{const f=await setup();try{await f.repo.save(f.principal,f.customer,{expectedRevision:0,answers:f.answers});await f.db.exec('CREATE ROLE fixture_app; GRANT USAGE ON SCHEMA vds_intake TO fixture_app; GRANT SELECT ON ALL TABLES IN SCHEMA vds_intake TO fixture_app; SET ROLE fixture_app;');assert.equal((await f.db.query('SELECT count(*)::int AS n FROM vds_intake.drafts')).rows[0].n,0);await f.db.transaction(async tx=>{await tx.query("SELECT set_config('vds.provider',$1,true),set_config('vds.subject',$2,true),set_config('vds.customer',$3,true)",[f.principal.provider,f.principal.id,f.customer]);assert.equal((await tx.query('SELECT count(*)::int AS n FROM vds_intake.drafts')).rows[0].n,1);assert.equal((await tx.query('SELECT count(*)::int AS n FROM vds_intake.outbox')).rows[0].n,0);await assert.rejects(tx.query('UPDATE vds_intake.versions SET payload=$1',[JSON.stringify({})]),/permission denied/);});}finally{await f.db.close();}});
test('local PostgreSQL: least-privilege app can save/enqueue but cannot change assignments or versions',async()=>{const f=await setup();try{await f.db.exec('SET ROLE vds_intake_app');await f.repo.save(f.principal,f.customer,{expectedRevision:0,answers:f.answers});const submission=await f.repo.submit(f.principal,f.customer,1);assert.equal(submission.status,'queued');await assert.rejects(f.db.query('UPDATE vds_intake.assignments SET revoked=false'),/permission denied/);await assert.rejects(f.db.query('DELETE FROM vds_intake.versions'),/permission denied/);await f.db.exec('RESET ROLE; SET ROLE vds_intake_worker');const claimed=await f.outbox.claim('worker');assert.equal(claimed.id,submission.id);await f.outbox.finish(claimed.lease,{verified:false});}finally{await f.db.close();}});
test('local PostgreSQL: private upload manifest ownership, pending exclusion and trusted completion',async()=>{const f=await setup();try{await f.repo.save(f.principal,f.customer,{expectedRevision:0,answers:f.answers});const manifest=await f.repo.beginPhoto(f.principal,f.customer,{itemId:'chair',mime:'image/png',size:10,sha256:'a'.repeat(64)});await assert.rejects(f.repo.save(f.principal,f.customer,{expectedRevision:1,answers:f.answers,photos:[manifest.id]}),e=>e.code==='PHOTO_NOT_READY');await assert.rejects(f.repo.completePhoto(f.principal,f.customer,manifest.id),e=>e.code==='UPLOAD_UNVERIFIED');f.repo.verifyPhoto=async m=>({...m,safe:true});await f.repo.completePhoto(f.principal,f.customer,manifest.id);assert.equal((await f.repo.save(f.principal,f.customer,{expectedRevision:1,answers:f.answers,photos:[manifest.id]})).photos[0],manifest.id);await assert.rejects(f.repo.completePhoto({...f.principal,id:'other'},f.customer,manifest.id),e=>e.code==='ACCESS_DENIED');}finally{await f.db.close();}});
