const {test}=require('node:test');
const assert=require('node:assert/strict');
const configured=async()=>({disableSignup:true,providers:{google:true}});
const policy=import('../src/session-policy.mjs').then(mod=>({createSessionHandler:(resolver,settings=configured)=>mod.createSessionHandler(resolver,settings)}));
const request=(scope='customer',method='GET')=>new Request('https://example.com/.netlify/functions/session?scope='+scope,{method});
test('anonymous session is rejected with 401 and never cached',async()=>{const {createSessionHandler}=await policy;const res=await createSessionHandler(async()=>null)(request());assert.equal(res.status,401);assert.match(res.headers.get('cache-control'),/no-store/)});
test('a verified customer can only access customer scope',async()=>{const {createSessionHandler}=await policy;const handle=createSessionHandler(async()=>({id:'test-customer',email:'customer@example.com'}));assert.equal((await handle(request())).status,200);assert.equal((await handle(request('owner'))).status,403)});
test('owner access requires exact server-controlled owner role',async()=>{const {createSessionHandler}=await policy;const handle=createSessionHandler(async()=>({id:'test-owner',email:'owner@example.com',roles:['owner']}));const res=await handle(request('owner'));assert.equal(res.status,200);assert.equal((await res.json()).access,'owner')});
test('user metadata and an owner-looking email cannot grant owner access',async()=>{const {createSessionHandler}=await policy;const handle=createSessionHandler(async()=>({id:'customer',email:'owner@example.com',userMetadata:{roles:['owner']},role:'owner'}));assert.equal((await handle(request('owner'))).status,403)});
test('malformed roles fail closed',async()=>{const {createSessionHandler}=await policy;for(const roles of ['owner',null,{},['Owner']])assert.equal((await createSessionHandler(async()=>({id:'customer',roles}))(request('owner'))).status,403)});
test('private tokens and raw metadata are not returned',async()=>{const {createSessionHandler}=await policy;const res=await createSessionHandler(async()=>({id:'test',email:'test@example.com',roles:['owner'],token:'test-secret',appMetadata:{confidential:'test-value'},userMetadata:{private:'test-value'}}))(request());assert.deepEqual(Object.keys(await res.json()).sort(),['access','email','id'])});
test('unknown scope and non-GET methods are rejected',async()=>{const {createSessionHandler}=await policy;const handle=createSessionHandler(async()=>({id:'test',roles:['owner']}));assert.equal((await handle(request('admin'))).status,400);assert.equal((await handle(request('customer','POST'))).status,405)});
test('identity service errors fail closed',async()=>{const {createSessionHandler}=await policy;const res=await createSessionHandler(async()=>{throw Error('secret internal error')})(request());assert.equal(res.status,503);assert.doesNotMatch(await res.text(),/secret/)});
test('browser draft guard protects unsaved edits even with saving selected',()=>{const fs=require('node:fs');const source=fs.readFileSync(require.resolve('../assets/js/brief.js'),'utf8');assert.match(source,/beforeunload[\s\S]*?if \(dirty\)/);assert.doesNotMatch(source,/dirty && !saveCheckbox.checked/)});

test('open registration or absent Google fails closed even for an owner',async()=>{const {createSessionHandler}=await policy;for(const settings of [{disableSignup:false,providers:{google:true}},{disableSignup:true,providers:{google:false}},{}]){const res=await createSessionHandler(async()=>({id:'owner',roles:['owner']}),async()=>settings)(request('owner'));assert.equal(res.status,503)}});
